# Generated by Django 5.2.4 on 2025-08-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Priority',
            field=models.CharField(choices=[('important', 'Important'), ('normal', 'Normal')], default='normal', max_length=10),
        ),
    ]
